# Site settings
title: "Jack Alvarez"
email: johnlee.alvarez@colorado.edu
description: ""
baseurl: ""
url: "http://jackalvarez.me"
title_description: |
  Hi I'm Jack. I am a San Diego native, attending the University of Colorado Boulder.
  During my time at CU, I am pursuing a degree in Computer Science.
title_image: "https://media.licdn.com/media/AAEAAQAAAAAAAAL-AAAAJGQwYzMyNTJkLTg2Y2YtNDZhOS04ZmMzLTEyN2JlOGYxZGE2Zg.jpg"
# google_analytics: "UA-20365477-4"
# disqus_account: cartenoire
github_repository: https://github.com/joal5752.github.io
# addthis_id: ra-513c6fa83da6ec67
post_limit: 5

# Social usernames/URLs
twitter_username: torchyhd
github_username:  joal5752
linkedin_link: http://linkedin.com/in/johnleealvarez/
# google_plus_link: http://carte-noire.jacobtomlinson.co.uk/
# stackoverflow_link: http://carte-noire.jacobtomlinson.co.uk/

# Footer
# footer_left: "Made with <i class=\"fa fa-heart\"></i> by <a href=\"https://twitter.com/_JacobTomlinson\">Jacob Tomlinson</a>"
# footer_right: "&lt;/&gt; on <a href=\"https://github.com/jacobtomlinson/carte-noire\">Github</a> &nbsp;<i class=\"fa fa-github-alt\"></i>"

# Build settings
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript"]
permalink: pretty
exclude: [vendor]
